

const ALERT = 'ALERT';

const REFETCH_CHATS = 'REFETCH_CHATS'

const NEW_ATTACHEMENTS = 'NEW_ATTACHEMENTS'

const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT'

export {
    ALERT, 
    REFETCH_CHATS,
    NEW_ATTACHEMENTS,
    NEW_MESSAGE_ALERT
}